# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hp\Desktop\srp\fastplot\project\main_demo\code\ui\font_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from utils.utils import ratio_size
from PyQt5 import QtCore, QtGui, QtWidgets
from utils import global_value


class Ui_font_module(object):
    """字体模块"""

    def __init__(self, file_modle) -> None:
        self.height_bias = self.height_bias()
        self.horizontal_bias = self.horizontal_bias()
        self.ratio_size =  ratio_size()
        self.app_path = global_value.get_value('app_path').replace('\\','/')
        self.setupUi(file_modle) 

    def height_bias(self) -> float:
        """竖直位置参数修正"""
        bias = 26.5 * ratio_size()
        return bias
    
    def horizontal_bias(self) -> float:
        """水平位置参数修正"""
        bias = 134 * ratio_size()
        return bias

    def setupUi(self, font_module):
        """框架"""

        font_module.setObjectName("font_module")
        font_module.resize(138 * ratio_size(), 51 * ratio_size())
        font = QtGui.QFont()
        font.setPointSize(6 * ratio_size())
        font.setUnderline(False)
        font_module.setFont(font)
        font_module.setStyleSheet("background-color: rgb(171, 171, 171);")
        
        #选择字体框
        self.fontComboBox = QtWidgets.QFontComboBox(font_module)
        self.fontComboBox.setGeometry(QtCore.QRect(11 * ratio_size() + self.horizontal_bias, 6 * ratio_size() + self.height_bias, 79 * ratio_size(), 14 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(6 * ratio_size())
        font.setUnderline(False)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n;"
                                        "alternate-background-color: rgb(255, 255, 255);\n;"
                                        "border-bottom-color: rgb(255, 255, 255);\n;"
                                        "font: 6pt '等线';")
        self.fontComboBox.setObjectName("fontComboBox")
        
        #选择字体大小框
        self.font_size_comboBox = QtWidgets.QComboBox(font_module)
        self.font_size_comboBox.setGeometry(QtCore.QRect(91 * ratio_size() + self.horizontal_bias, 6 * ratio_size() + self.height_bias, 34 * ratio_size(), 14 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(6 * ratio_size())
        self.font_size_comboBox.setFont(font)
        self.font_size_comboBox.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n;"
                                              "alternate-background-color: rgb(255, 255, 255);\n;"
                                              "font: 6pt '等线';")
        self.font_size_comboBox.setObjectName("font_size_comboBox")
        self.font_size_comboBox.addItems(['4','9','12'])

        #字体加粗
        self.font_bold = QtWidgets.QPushButton(font_module)
        self.font_bold.setGeometry(QtCore.QRect(11 * ratio_size() + self.horizontal_bias, 21 * ratio_size() + self.height_bias, 14 * ratio_size(), 16 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75 * ratio_size())
        self.font_bold.setFont(font)
        self.font_bold.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.font_bold.setObjectName("font_bold")
        
        #斜体
        self.font_Italics = QtWidgets.QPushButton(font_module)
        self.font_Italics.setGeometry(QtCore.QRect(25 * ratio_size() + self.horizontal_bias, 21 * ratio_size() + self.height_bias, 14 * ratio_size(), 16 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50 * ratio_size())
        self.font_Italics.setFont(font)
        self.font_Italics.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.font_Italics.setObjectName("font_Italics")
        
        #下划线
        self.font_underline = QtWidgets.QPushButton(font_module)
        self.font_underline.setGeometry(QtCore.QRect(39 * ratio_size() + self.horizontal_bias, 20 * ratio_size() + self.height_bias, 15 * ratio_size(), 18 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50 * ratio_size())
        self.font_underline.setFont(font)
        self.font_underline.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.font_underline.setObjectName("font_underline")
        
        #上标
        self.font_up = QtWidgets.QPushButton(font_module)
        self.font_up.setGeometry(QtCore.QRect(54 * ratio_size() + self.horizontal_bias, 20 * ratio_size() + self.height_bias, 15 * ratio_size(), 15 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50 * ratio_size())
        self.font_up.setFont(font)
        self.font_up.setStyleSheet("border-image: url(" + self.app_path + "/graph/up.png)\n")
        self.font_up.setText("")
        self.font_up.setObjectName("font_up")
        
        #下标
        self.font_down = QtWidgets.QPushButton(font_module)
        self.font_down.setGeometry(QtCore.QRect(69 * ratio_size() + self.horizontal_bias, 21 * ratio_size() + self.height_bias, 15 * ratio_size(), 15 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50 * ratio_size())
        self.font_down.setFont(font)
        self.font_down.setStyleSheet("border-image: url(" + self.app_path + "/graph/down.png)\n")
        self.font_down.setText("")
        self.font_down.setObjectName("font_down")
        
        #上下标
        self.font_updown = QtWidgets.QPushButton(font_module)
        self.font_updown.setGeometry(QtCore.QRect(85 * ratio_size() + self.horizontal_bias, 21 * ratio_size() + self.height_bias, 15 * ratio_size(), 15 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50 * ratio_size())
        self.font_updown.setFont(font)
        self.font_updown.setStyleSheet("border-image: url(" + self.app_path + "/graph/up_down.png)\n")
        self.font_updown.setText("")
        self.font_updown.setObjectName("font_updown")
        
        #模块分割线
        self.line = QtWidgets.QFrame(font_module)
        self.line.setGeometry(QtCore.QRect(138 * ratio_size() + self.horizontal_bias, 0 * ratio_size() + self.height_bias, 5 * ratio_size(), 48 * ratio_size()))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(6 * ratio_size())
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75 * ratio_size())
        self.line.setFont(font)
        self.line.setStyleSheet("background-color: rgb(247, 240, 240);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(font_module)
        self.line_2.setGeometry(QtCore.QRect(102 * ratio_size() + self.horizontal_bias, 21 * ratio_size() + self.height_bias, 5 * ratio_size(), 15 * ratio_size()))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(6 * ratio_size())
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75 * ratio_size())
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background-color: rgb(247, 240, 240);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        
        #字体颜色
        self.font_color = QtWidgets.QPushButton(font_module)
        self.font_color.setGeometry(QtCore.QRect(106 * ratio_size() + self.horizontal_bias, 22 * ratio_size() + self.height_bias, 15 * ratio_size(), 15 * ratio_size()))
        font = QtGui.QFont()
        font.setPointSize(8 * ratio_size())
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50 * ratio_size())
        self.font_color.setFont(font)
        self.font_color.setStyleSheet("border-image: url(" + self.app_path + "/graph/font_color.png)\n")
        self.font_color.setText("")
        self.font_color.setObjectName("font_color")
        
        #模块名称
        self.name_font = QtWidgets.QLabel(font_module)
        self.name_font.setGeometry(QtCore.QRect(57 * ratio_size() + self.horizontal_bias, 38 * ratio_size() + self.height_bias, 17 * ratio_size(), 12 * ratio_size()))

        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(6 * ratio_size())
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75 * ratio_size())
        self.name_font.setFont(font)
        self.name_font.setStyleSheet("background-color: rgb(247, 240, 240);")
        self.name_font.setObjectName("name_font")

        self.retranslateUi(font_module)
        QtCore.QMetaObject.connectSlotsByName(font_module)

    def retranslateUi(self, font_module):
        _translate = QtCore.QCoreApplication.translate
        font_module.setWindowTitle(_translate("font_module", "Form"))
        self.font_bold.setText(_translate("font_module", "B"))
        self.font_Italics.setText(_translate("font_module", "I"))
        self.font_underline.setText(_translate("font_module", "U"))
        self.name_font.setText(_translate("font_module", "字体"))

    def module_hide(self):
        """隐藏状态"""

        self.fontComboBox.hide()
        self.font_size_comboBox.hide()
        self.font_bold.hide()
        self.font_Italics.hide()
        self.font_underline.hide()
        self.font_up.hide()
        self.font_down.hide()
        self.font_updown.hide()
        self.line.hide()
        self.line_2.hide()
        self.font_color.hide()
        self.name_font.hide()

    def module_show(self):
        """显示状态"""

        self.fontComboBox.show()
        self.font_size_comboBox.show()
        self.font_bold.show()
        self.font_Italics.show()
        self.font_underline.show()
        self.font_up.show()
        self.font_down.show()
        self.font_updown.show()
        self.line.show()
        self.line_2.show()
        self.font_color.show()
        self.name_font.show()
