# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hp\Desktop\srp\fastplot\project\main_demo\ui\main_framework.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from utils.utils import ratio_size, window_size
from PyQt5 import QtCore, QtGui, QtWidgets
from file_framework import Ui_file_module
from font_module import Ui_font_module
from data_analysis_module import data_analysis_module
from image_pattern import image_pattern_module
from Common_format import Ui_common_format_module
from page_module import page_block_module
from utils import global_value



class Ui_MainWindow(object):


    def setupUi(self, MainWindow, title_height):
        """主页面框架"""

        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: rgb(171, 171, 171);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #功能区标题栏
        self.domain_header = QtWidgets.QLabel(self.centralwidget)
        self.domain_header.setGeometry(QtCore.QRect(0, 0, 10000, 23 * ratio_size()))
        self.domain_header.setStyleSheet("background-color: rgb(225, 128, 78);")
        self.domain_header.setObjectName("domain_header")
        
        #功能区
        self.domain_area = QtWidgets.QLabel(self.centralwidget)
        self.domain_area.setGeometry(QtCore.QRect(0, 23 * ratio_size(), 10000, 55 * ratio_size()))
        self.domain_area.setStyleSheet("background-color: rgb(247, 240, 240);")
        self.domain_area.setObjectName("domain_area")
        
        #页面区栏
        self.page_bar = QtWidgets.QLabel(self.centralwidget)
        self.page_bar.setGeometry(QtCore.QRect(0, 78 * ratio_size(), 10000, 16* ratio_size()))
        self.page_bar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:10, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(230, 230, 230, 255));\n")
        self.page_bar.setObjectName("page_bar")
        
        #功能按钮（主页）
        self.Homepage_Button_main = QtWidgets.QPushButton(self.centralwidget)
        self.Homepage_Button_main.setGeometry(QtCore.QRect(4 * ratio_size(), 4 * ratio_size(), 64 * ratio_size(), 23 * ratio_size()))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(int(8 * ratio_size()))
        font.setBold(False)
        font.setWeight(50)
        self.Homepage_Button_main.setFont(font)
        self.Homepage_Button_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Homepage_Button_main.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                "border-style: outside;\n"
                                                "background-color: rgba(247, 240, 240, 255);\n"
                                                "color: rgb(0, 0, 0);")
        self.Homepage_Button_main.setObjectName("Homepage_Button_main")
        self.Homepage_Button_main.clicked.connect(self.click_main)

        #功能按钮（绘图）
        self.Homepage_Button_paint = QtWidgets.QPushButton(self.centralwidget)
        self.Homepage_Button_paint.setGeometry(QtCore.QRect(73 * ratio_size() , 4 * ratio_size(), 64 * ratio_size(), 23 * ratio_size()))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(int(8 * ratio_size()))
        font.setBold(False)
        font.setWeight(50)
        self.Homepage_Button_paint.setFont(font)
        self.Homepage_Button_paint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Homepage_Button_paint.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                 "border-style: outside;\n"
                                                 "background-color: rgba(247, 240, 240, 0);\n"
                                                 "color: rgb(255, 255, 255);")
        self.Homepage_Button_paint.setObjectName("Homepage_Button_paint")
        self.Homepage_Button_paint.clicked.connect(self.click_paint)
        
        #功能按钮（帮助）
        self.Homepage_Button_help = QtWidgets.QPushButton(self.centralwidget)
        self.Homepage_Button_help.setGeometry(QtCore.QRect(142 * ratio_size(), 4 * ratio_size(), 64 * ratio_size(), 23 * ratio_size()))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(int(8 * ratio_size()))
        font.setBold(False)
        font.setWeight(50)
        self.Homepage_Button_help.setFont(font)
        self.Homepage_Button_help.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Homepage_Button_help.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                "border-style: outside;\n"
                                                "background-color: rgba(247, 240, 240, 0);\n"
                                                "color: rgb(255, 255, 255);")
        self.Homepage_Button_help.setObjectName("Homepage_Button_help")
        self.Homepage_Button_help.clicked.connect(self.click_help)
        
        MainWindow.setCentralWidget(self.centralwidget)

        #状态栏
        self.status_bar = QtWidgets.QLabel(MainWindow)
        self.status_bar.setGeometry(QtCore.QRect(0, 
                                                 window_size()[1] - 0.75 * title_height - 11 * ratio_size(), # 0.75 ?
                                                 10000,                                                      # !!!
                                                 11* ratio_size()))
        
        self.status_bar.setStyleSheet("background-color: rgb(243, 242, 241)")
        self.status_bar.setObjectName("status_bar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #文件模块
        self.file_framework = Ui_file_module(MainWindow)         

        #字体模块
        self.font_module = Ui_font_module(MainWindow)

        #数据分析模块
        self.data_analysis_module = data_analysis_module(MainWindow)

        #图像样式模块(隐藏)
        self.image_pattern_module = image_pattern_module(MainWindow, title_height)
        self.image_pattern_module.module_hide()

        #常用图像模块(隐藏)
        self.common_format_module = Ui_common_format_module(MainWindow)
        self.common_format_module.module_hide()

        #页面控件
        self.page_module = page_block_module(MainWindow, title_height)
 
         
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fastplot 1.0"))
        self.Homepage_Button_main.setText(_translate("MainWindow", "主页"))
        self.Homepage_Button_paint.setText(_translate("MainWindow", "绘图"))
        self.Homepage_Button_help.setText(_translate("MainWindow", "帮助"))


class Main_window(Ui_MainWindow):

    def click_main(self):
        """按下页面按钮"""

        #点亮主页图标
        self.Homepage_Button_main.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n" 
                                                "border-style: outside;\n" 
                                                "background-color: rgba(247, 240, 240, 255);\n" 
                                                "color: rgb(0, 0, 0);")

        self.Homepage_Button_paint.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                 "border-style: outside;\n"
                                                 "background-color: rgba(247, 240, 240, 0);\n"
                                                 "color: rgb(255, 255, 255);")

        self.Homepage_Button_help.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                "border-style: outside;\n"
                                                "background-color: rgba(247, 240, 240, 0);\n"
                                                "color: rgb(255, 255, 255);")     
        
        #显示主页模块
        
        self.file_framework.module_show()
        self.font_module.module_show()
        self.data_analysis_module.module_show()

        #隐藏绘图模块
        self.image_pattern_module.module_hide()
        self.common_format_module.module_hide()

        #隐藏帮助模块

    def click_paint(self):
        """按下绘图按钮"""
        
        #点亮绘图模块
        self.Homepage_Button_main.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n" 
                                                "border-style: outside;\n" 
                                                "background-color: rgba(247, 240, 240, 0);\n" 
                                                "color: rgb(255, 255, 255);")

        self.Homepage_Button_paint.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                 "border-style: outside;\n"
                                                 "background-color: rgba(247, 240, 240, 255);\n"
                                                 "color: rgb(0, 0, 0);")

        self.Homepage_Button_help.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                "border-style: outside;\n"
                                                "background-color: rgba(247, 240, 240, 0);\n"
                                                "color: rgb(255, 255, 255);")
        
        #隐藏主页模块
        self.file_framework.module_hide()
        self.font_module.module_hide()
        self.data_analysis_module.module_hide()

        #显示绘图模块
        self.image_pattern_module.module_show()
        self.common_format_module.module_show()

        #隐藏帮助模块


    def click_help(self):
        """按下帮助按钮"""
        
        #点亮绘图模块图标
        self.Homepage_Button_main.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n" 
                                                "border-style: outside;\n" 
                                                "background-color: rgba(247, 240, 240, 0);\n" 
                                                "color: rgb(255, 255, 255);")

        self.Homepage_Button_paint.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                 "border-style: outside;\n"
                                                 "background-color: rgba(247, 240, 240, 0);\n"
                                                 "color: rgb(255, 255, 255);")

        self.Homepage_Button_help.setStyleSheet("border-radius: "+str(6 * ratio_size())+"px;\n"
                                                "border-style: outside;\n"
                                                "background-color: rgba(247, 240, 240, 255);\n"
                                                "color: rgb(0, 0, 0);")
        
        #隐藏主页模块
        self.file_framework.module_hide()
        self.font_module.module_hide()
        self.data_analysis_module.module_hide()

        #隐藏绘图模块
        self.image_pattern_module.module_hide()
        self.common_format_module.module_hide()

        #显示帮助模块

